### ISSUE TITLE
Notice regarding AuroraProxy Documentation

### ISSUE THREAD

**Issue by deopdeop** [titaniumnetwork-dev/Aurora#27]
As this project advances, we will move documentation from README.md to a github wiki where topics will be explained in detail

**Comment by Rockpods** [comment]
cool

**Comment by Nickbutno** [comment]
HIII GUYSS

**Comment by easella** [comment]
how to clone the respository and start the server in bash? Without the sudo command.

**Comment by nevr13** [comment]
rip aurora, development is severely limited or the proxy is down.

**Comment by deopdeop** [comment]
Aurora dead
