### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by xtc-dev** [titaniumnetwork-dev/Aurora#3]
I've heard the release of this proxy has been hyped up for awhile, and I'd like to know, does it run sites with captcha? That was one of the major things people talked about when discussing this proxy.

**Comment by ghost** [comment]
It hasn't been made yet. This is very much a WIP. That is on the road map though.

Who are you by the way?

**Comment by xtc-dev** [comment]
The Among Us Proxy Maker, of course! Check my repos for proof!

**Comment by QuiteAFancyEmerald** [comment]
Oh nice.

**Comment by boomermath** [comment]
POG

**Comment by Rockpods** [comment]
MY CHILDREN... WHERE ARE THEY

**Comment by xtc-dev** [comment]
I ate them.
