### ISSUE TITLE
heroku deployment methods

### ISSUE THREAD

**Issue by nevr13** [titaniumnetwork-dev/Aurora#69]
is it possible to deploy this to heroku with the Deploy To Heroku button?

**Comment by deopdeop** [comment]
Yes

**Comment by nevr13** [comment]
there isnt a way tho

**Comment by deopdeop** [comment]
yes there is

**Comment by nevr13** [comment]
is there a deploy to heroku button in readme.md? i dont see one.

**Comment by Proxuser1** [comment]
ok but how do you deploy to heroku as I dont understand

**Comment by nevr13** [comment]
https://www.google.com/url?sa=i&url=https%3A%2F%2Fblog.heroku.com%2Fheroku-button&psig=AOvVaw278oNv-TBhnjHPzrKmqchf&ust=1616612748663000&source=images&cd=vfe&ved=0CAYQjRxqFwoTCMCitPmNx-8CFQAAAAAdAAAAABAD Can i do this? NOTE: that was an example.

**Comment by QuiteAFancyEmerald** [comment]
It's still being worked on and Aurora is nowhere near being a final product right now.
